# Generated by Django 4.1.4 on 2022-12-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.FloatField(default=0.0)),
                ('prix', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='nom',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='prenom',
            field=models.CharField(default='', max_length=50),
        ),
    ]
