# Generated by Django 4.1.4 on 2022-12-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAnnonce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='title',
            field=models.CharField(default='', max_length=35),
        ),
    ]
