# Generated by Django 4.1.4 on 2023-01-03 16:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAnnonce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('send_date', models.DateTimeField(auto_now=True)),
                ('sent_to', models.ManyToManyField(default='', related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
