# Generated by Django 4.1.4 on 2022-12-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAnnonce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='photo%y%m%d'),
        ),
    ]
