# Generated by Django 4.1.4 on 2023-01-06 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAnnonce', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='send_date',
            new_name='created_at',
        ),
    ]
