# Generated by Django 4.1.4 on 2023-01-03 23:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAnnonce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annoncement',
            name='favorated_by',
            field=models.ManyToManyField(default='', related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='annoncementimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/photo%y%m%d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/photo%y%m%d'),
        ),
    ]
