# Generated by Django 4.1.4 on 2022-12-29 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAnnonce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='creation_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
