# Generated by Django 4.1.4 on 2022-12-24 17:32

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAnnonce', '0002_remove_annonce_localization_alter_location_commune_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='commune',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='wilaya', chained_model_field='wilaya', default='', on_delete=django.db.models.deletion.CASCADE, related_name='location', to='gestionAnnonce.commune'),
        ),
    ]
