# Generated by Django 4.1.4 on 2023-01-06 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAnnonce', '0002_rename_send_date_messages_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='created_at',
        ),
    ]
