# Generated by Django 4.1.4 on 2022-12-24 13:22

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAnnonce', '0002_remove_annonce_localization_alter_location_commune_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='location',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestionAnnonce.location'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='wilaya',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='Commune', to='gestionAnnonce.wilaya'),
        ),
        migrations.AlterField(
            model_name='location',
            name='commune',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='wilaya', chained_model_field='wilaya', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='gestionAnnonce.commune'),
        ),
        migrations.AlterField(
            model_name='location',
            name='wilaya',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='gestionAnnonce.wilaya'),
        ),
    ]
