# Generated by Django 4.1.4 on 2023-01-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAnnonce', '0002_annoncement_favorated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annoncement',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
