# Generated by Django 4.1.4 on 2022-12-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAnnonce', '0002_alter_annonce_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caregorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cat', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=20)),
                ('prenom', models.CharField(default='', max_length=20)),
                ('adresse', models.TextField(blank=True)),
                ('tele', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_type', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Annonce',
        ),
    ]
