# Generated by Django 4.1.4 on 2023-01-03 16:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAnnonce', '0003_message_sent_by_alter_message_sent_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_by',
            field=models.ManyToManyField(default='', related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_to',
            field=models.ManyToManyField(default='', related_name='message', to=settings.AUTH_USER_MODEL),
        ),
    ]
