# Generated by Django 4.1.4 on 2022-12-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAnnonce', '0003_annonce_location_alter_commune_wilaya_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='title',
            field=models.CharField(default='', max_length=30),
        ),
    ]
