# Generated by Django 4.1.4 on 2023-01-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAnnonce', '0003_annoncement_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annoncement',
            name='deleted',
            field=models.BooleanField(),
        ),
    ]
