# Generated by Django 4.1.4 on 2022-12-22 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAnnonce', '0003_caregorie_contact_type_delete_annonce'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.FloatField(default=0.0)),
                ('prix', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='photo%y%m%d')),
                ('caregorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonce', to='gestionAnnonce.caregorie')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonce', to='gestionAnnonce.contact')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonce', to='gestionAnnonce.type')),
            ],
        ),
    ]
