# Generated by Django 4.1.4 on 2023-01-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAnnonce', '0004_messages_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Read', 'Read')], default='Pending', max_length=15),
        ),
    ]
