# Generated by Django 4.1.4 on 2023-01-03 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAnnonce', '0004_alter_message_sent_by_alter_message_sent_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sent_by',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sent_to',
        ),
        migrations.AddField(
            model_name='message',
            name='sent_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='sent_to',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='message', to=settings.AUTH_USER_MODEL),
        ),
    ]
