# Generated by Django 4.1.4 on 2022-12-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAnnonce', '0004_annonce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='nom',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='prenom',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='type',
            name='nom_type',
            field=models.CharField(max_length=20),
        ),
    ]
