# Generated by Django 4.1.4 on 2022-12-22 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAnnonce', '0005_alter_contact_nom_alter_contact_prenom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='caregorie',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='type',
        ),
    ]
