# Generated by Django 4.1.4 on 2022-12-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAnnonce', '0006_remove_annonce_caregorie_remove_annonce_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='kk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k', models.CharField(max_length=20)),
            ],
        ),
    ]
