# Generated by Django 4.1.4 on 2022-12-22 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAnnonce', '0007_kk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kk',
        ),
        migrations.AddField(
            model_name='annonce',
            name='caregorie',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='annonce', to='gestionAnnonce.caregorie'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='contact',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='annonce', to='gestionAnnonce.contact'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='annonce', to='gestionAnnonce.type'),
        ),
    ]
