# Generated by Django 4.1.4 on 2023-01-06 02:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAnnonce', '0008_alter_annoncement_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annoncement',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
