"""
Django settings for annonces_immobilieres project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import dj_database_url
import cloudinary_storage

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_paw!m32fimv^uv+whwku-itgfyd+6v&84vqbtuxy^^orhdb2^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['.vercel.app','127.0.0.1',]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework.authtoken',#for token 
    'rest_framework',
    'smart_selects',    #for the chained forienkey 
    'phone_field',  #for phone number validation
    'gestionAnnonce.apps.GestionannonceConfig',
    'corsheaders',
    'cloudinary',
    'cloudinary_storage'
]
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': 
    ['rest_framework.authentication.TokenAuthentication'],
    #globale authentication with token
    'DEFAULT_PERMISSION_CLASSES':
    ['rest_framework.permissions.IsAuthenticated'],

}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
]

ROOT_URLCONF = 'annonces_immobilieres.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'annonces_immobilieres.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
import os
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'tp_igl',
        'USER': 'tp_igle_user',
        'PASSWORD': '9ZmLj0Imr37kxqvf4z5CgS8SzLZn9mcK',
        'HOST':'dpg-cetgefpgp3jmgl0u60cg-a',
        'PORT':'5432',
    }
}

DATABASES['default'] = dj_database_url.parse(
    # 'postgres://tp_igle_user:9ZmLj0Imr37kxqvf4z5CgS8SzLZn9mcK@dpg-cetgefpgp3jmgl0u60cg-a.oregon-postgres.render.com/tp_igle',
    'postgres://tp_igl_user:oe6YTQ7VMEEtOTGTSFUIW7yvh8FV1HO7@dpg-ceu4arg2i3mj6pkhf0n0-a.oregon-postgres.render.com/tp_igl',
    conn_max_age=600,
    conn_health_checks=True,
)

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field


#allows the usage of smart selcts
USE_DJANGO_JQUERY = True
AUTH_USER_MODEL = 'gestionAnnonce.User'
USE_DJANGO_JQUERY = True
AUTH_USER_MODEL = 'gestionAnnonce.User'
CORS_ORIGIN_ALLOW_ALL = True
CORS_ORIGIN_WHITELIST = (
'http://localhost:5173',
)
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

STATICFILES_DIRS = os.path.join(BASE_DIR, 'static'),
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles_build', 'static')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

CLOUDINARY_STORAGE = {
    'CLOUD_NAME' : 'dfhnkisz4',
    'API_KEY' : '653263892964524',
    'API_SECRET' : "LlxNwXneYaz2u1-12r0disakQms",
}

DEFAULT_FILE_STORAGE= 'cloudinary_storage.storage.MediaCloudinaryStorage'